package io.tyloo.core.exception;

/*
 *
 * 确认异常
 *
 * @Author:Zh1Cheung 945503088@qq.com
 * @Date: 19:59 2019/12/4
 *
 */
public class ConfirmingException extends RuntimeException {

    public ConfirmingException(Throwable cause) {
        super(cause);
    }
}
